### ISSUE TITLE
SDK fails to work with VirtualBox 5.0.12

### ISSUE THREAD

**Issue by dleslie** [NextThingCo/CHIP-SDK#11]
Using Virtual Box 5.0.12 the following occurs:

```
vagrant up
Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
```

**Comment by zendes** [comment]
what version of vagrant are you using? I'm using 1.8.1 from https://www.vagrantup.com/downloads.html, and it works with the latest virtualbox 5.0.12 from https://www.virtualbox.org/wiki/Downloads

I'm running ubuntu 14.04 x86_64 as a host os.

**Comment by dleslie** [comment]
Ah, I didn't realize that could be the issue. It's 1.4.3-1, I'm running ubuntu 14.04 x86_64 as well.
