### ISSUE TITLE
Improvement suggestion for README.md

### ISSUE THREAD

**Issue by armijnhemel** [NextThingCo/CHIP-SDK#3]
There are a few improvements I would suggest:

1. following the instructions in README.md the git repository will be cloned into CHIP-SDK. In the documentation it is assumed that the repository is cloned into a directory called "chip_sdk". To avoid confusion I would either fix the instructions for cloning the git repositoru, or change "chip_sdk" into "CHIP-SDK" in the documentation.

2. I would clarify why the extension pack is needed. It is a piece of non-free software, which people will not like (and it will draw out some criticism). I guess it is because of mounting /vagrant and the USB 2.0 support.

**Comment by kaplan2539** [comment]
Thanks alot. I have revised README.md.
