### ISSUE TITLE
creating own buildimage

### ISSUE THREAD

**Issue by mrlowalowa** [NextThingCo/CHIP-SDK#6]
I just managed to create my own little .config

but when I hit make than it says 'hg' is missing

I think it is not that hard to fix but implementing it direct into the SDK would be helpful

**Comment by tpetazzoni** [comment]
@mrlowalowa Whether `hg` is needed or not depends on the selection of packages you have made. `hg` is only needed if you have a selected a package that needs to be fetched from a Mercurial repository. And only 6 packages in Buildroot are fetched from a Mercurial repository. Therefore, it is quite logical for the CHIP-SDK to not have Mercurial pre-installed. You can install it very simply if you need it.

I believe this issue can be closed as "wontfix".
